version: "3.8"

services:
  backend:
    build: .
    container_name: django_backend
    ports:
      - "8003:8003"
    volumes:
      - .:/app  
      - ./db.sqlite3:/app/db.sqlite3  
    environment:
      - DEBUG=True
    restart: always
