googleProvider:
  service: google-trends
  baseUrl: https://trends.google.com/trends
  endpoint: trendingsearches
  timeRange: daily
  region: NG

newsProvider:
  - service: newsapi
    baseUrl: https://newsapi.org/v2
    endpoint: everything