googleProvider:
  service: google-trends
  base_api_url: https://trends.google.com/trends
  trending_searches: /trendingsearches
  time_frame: /daily
  query_params: ?geo=
  region: NG

newsProvider:
  - service: newsapi
    base_api_url: https://newsapi.org/v2
    source: /everything
    query_params: ?q=