AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Poll Service for P2P Bets


Parameters:
  # General
  RootStackName:
    Type: String
    Description: Name of the root stack
  EnvironmentName:
    Type: String
    Description: Name of the target environment (e.g., dev or prod)
  S3BucketName:
    Type: String
    Description: S3 bucket name
    Default: p2p-bets-poll-artifacts
  ImageTag:
    Type: String
    Description: Image tag for the handler
    Default: 'latest'
  # Networking
  LambdaSecurityGroupId:
    Type: String
    Description: ID of the security group for Lambda functions
  PrivateSubnetId:
    Type: String
    Description: ID of the private subnet for Lambda functions

Resources:
  # IAM Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'PollServiceLambdaRole-${EnvironmentName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Policies:
        - PolicyName: SharedPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Shared permissions for both Lambda and EC2
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${EnvironmentName}/odds/api-*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${RootStackName}-PollService-*'
              # Lambda-specific permissions
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'  # <-- Indentation here

  PollService:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: !Sub '${RootStackName}-PollService-${EnvironmentName}'
      Code:
        ImageUri: !Sub '864899853095.dkr.ecr.${AWS::Region}.amazonaws.com/p2p-bets-poll-${EnvironmentName}:pollservice_${EnvironmentName}_${ImageTag}'
      PackageType: Image
      Timeout: 90
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetId
      Environment:
        Variables:
          ENV: !Ref EnvironmentName
          REGION: !Ref AWS::Region

Outputs:
  PollServiceArn:
    Description: ARN of the PollService Lambda function
    Value: !GetAtt PollService.Arn
    Export:
      Name: !Sub '${EnvironmentName}-PollServiceArn'
