AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Multiple SAM applications with shared resources.


Parameters:
  EnvironmentName:
    Type: String
    Description: Name of the target environment
  S3BucketName:
    Type: String
    Description: S3 bucket name
    Default: p2p-bets-artifacts

Resources:
  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3BucketName}/${EnvironmentName}/Infrastructure/Poll/Api/template.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        PollFunctionArn:
          Fn::ImportValue:
            !Sub '${EnvironmentName}-PollFunctionArn'

  PollFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3BucketName}/${EnvironmentName}/Service/Poll/Lambda/template.yaml'
      Parameters:
        RootStackName: !Ref 'AWS::StackName'
        EnvironmentName: !Ref EnvironmentName