name: P2P BETS CI/CD


on:
  push:
    branches:
      - Production
      - Staging
      - Development
  pull_request:
    branches:
      - Production

jobs:
  validate-cfn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Validate all CloudFormation templates
        run: python3 ./Scripts/validate_templates.py

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

  build:
    needs: [validate-cfn, test]
    uses: ./.github/workflows/docker-build.yml
    with:
        branch: ${{ github.ref_name }}
        environment: ${{ matrix.environment }}
        region:  ${{ matrix.region }}
        application-name: P2P-BETS-POLL-AI
        application-tag: ${{ github.sha }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - environment: Production
            region: us-east-1
          - environment: Staging
            region: us-east-2
          - environment: Development
            region: us-west-2