name: P2P BETS CI/CD


on:
  push:
    branches:
      - Production
      - Staging
      - Development
  pull_request:
    branches:
      - Production

jobs:
  validate-cfn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Validate all CloudFormation templates
        run: python3 ./Scripts/validate_templates.py

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

  build:
    needs: [validate-cfn, test]
    uses: ./.github/workflows/docker-build.yml
    with:
        branch: ${{ github.ref_name }}
        environment: ${{ matrix.environment }}
        region:  ${{ matrix.region }}
        application-name: p2p-bets-poll
        application-tag: ${{ github.sha }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - branch: Development
            environment: dev
            region: us-west-2
            application-name: PollServiceApplication
          # - branch: Staging
          #   environment: stage
          #   region: us-east-2
          #   application-name: PollServiceApplication
          # - branch: Production 
          #   environment: prod
          #   region: us-east-1
          #   application-name: PollServiceApplication
  
  deploy-infra-and-networking:
    needs: [build]
    uses: ./.github/workflows/cfn-deploy.yml
    with:
      build-type: 'infrastructure'
      environment: ${{ matrix.environment }}
      region: ${{ matrix.region }}
      branch: ${{ matrix.branch }}
      application-tag: ${{ github.sha }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - branch: Development
            environment: dev
            region: us-west-2
          # - branch: Staging
          #   environment: stage
          #   region: us-east-2
          # - branch: Production
          #   environment: prod
          #   region: us-east-1

  deploy-lambda-infra:
    needs: [deploy-infra-and-networking, build]
    if: always() && needs.deploy-infra-and-networking.result == 'success'
    uses: ./.github/workflows/cfn-deploy.yml
    with:
      build-type: 'lambda'
      environment: ${{ matrix.environment }}
      region: ${{ matrix.region }}
      application-tag: ${{ github.sha }}
      branch: ${{ matrix.branch }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - branch: Development
            environment: dev
            region: us-west-2
          # - branch: Staging
          #   environment: stage
          #   region: us-east-2
          # - branch: Production
          #   environment: prod
          #   region: us-east-1
  
  deploy-api:
    needs: deploy-lambda-infra
    uses: ./.github/workflows/cfn-deploy.yml
    with:
      build-type: 'api'
      environment: ${{ matrix.environment }}
      region: ${{ matrix.region }}
      branch: ${{ matrix.branch }}
      application-tag: ${{ github.sha }}
    permissions:
      id-token: write
      contents: read
    strategy:
        matrix:
            include:
              - branch: Development
                environment: dev
                region: us-west-2
              # - branch: Staging
              #   environment: stage
              #   region: us-east-2
              # - branch: Production
              #   environment: prod
              #   region: us-east-1