name: Reusable Build and Packaging Workflow


on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
      region:
        required: true
        type: string
      application-name:
        required: true
        type: string
      application-tag:
        required: true
        type: string

jobs:
  build-and-package:
    if: ${{ inputs.branch == github.ref_name }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::864899853095:role/GitHubActionsDeployRole
          aws-region: ${{ inputs.region }}

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin 864899853095.dkr.ecr.${{ inputs.region }}.amazonaws.com


      - name: Ensure ECR Repository Exists
        run: |
          aws ecr describe-repositories --repository-names p2p-bets-image-${{ inputs.environment }} --region ${{ inputs.region }} || \
          aws ecr create-repository --repository-name p2p-bets-image-${{ inputs.environment }} --region ${{ inputs.region }}

      - name: Build Docker Image
        run: |
          APPLICATION_NAME=$(echo "${{ inputs.application-name }}" | tr '[:upper:]' '[:lower:]')
          docker build --platform linux/amd64 \
            -f ./Dockerfile \
            -t ${APPLICATION_NAME}-${{ inputs.environment }} .

      - name: Tag Docker image
        run: |
          APPLICATION_NAME=$(echo "${{ inputs.application-name }}" | tr '[:upper:]' '[:lower:]')
          docker tag ${APPLICATION_NAME}-${{ inputs.environment }} 864899853095.dkr.ecr.${{ inputs.region }}.amazonaws.com/p2p-bets-image-${{ inputs.environment }}:${APPLICATION_NAME}_${{ inputs.environment }}_${{ inputs.application-tag }}
          docker push 864899853095.dkr.ecr.${{ inputs.region }}.amazonaws.com/p2p-bets-image-${{ inputs.environment }}:${APPLICATION_NAME}_${{ inputs.environment }}_${{ inputs.application-tag }}